# Generated by Django 6.0.4 on 2026-05-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='online_payment_method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('paymaya', 'PayMaya'), ('credit_card', 'Credit Card'), ('other', 'Other Transaction')], max_length=20, null=True),
        ),
    ]
